### ISSUE TITLE
NC 23 to 24 question.

### ISSUE THREAD

**Issue by slimshizn** [RocketChat/rocketchat_nextcloud#34] opened 2022-09-29 02:28 UTC
When updating from ``23.0.9 - 24.0.5``, will rocket.chat still function correctly or are there breaking changes``?`` Thanks.

**Comment by trivoallan** [comment] 2022-09-29 08:32
I'm trying to setup the app on a 24.0.5 NC instance on a Hetzner Storage Share and it does not work.

Hetzner support tells me : 
>We can not see any errors in our log, but it looks like this app is not working with Nextcloud Version 24.

Indeed, NC 24 is not listed on the app marketplace page : https://apps.nextcloud.com/apps/rocketchat_nextcloud

**Comment by trivoallan** [comment] 2022-09-29 08:33
This issue seems to be a duplicate of #27

**Comment by slimshizn** [comment] 2022-09-29 14:15
@trivoallan #27 asks when it's going to be released for the latest Nextcloud release, I'm asking if it ``still functions``. I don't want to update if it does not. Thank you for the confirmation that it does not work. I will stay with 23.

**Closed as completed** 2022-09-29 14:18 UTC
